productpage:
  namespace: bookinfo-dev
  image: registry.arpo.ml/bookinfo/productpage
  tag: dev
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 9080
  healthCheckPath: "/health"
ingress:
  host: dev.arpo.ml
  path: "/"
  serviceType: ClusterIP
  annotations:
    kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/rewrite-target: /$2
extraEnv:
  COMMIT_ID: CHANGEME
  DETAILS_HOSTNAME: https://dev.arpo.ml/details
  RATINGS_HOSTNAME: https://dev.arpo.ml/ratings
  REVIEWS_HOSTNAME: https://dev.arpo.ml/reviews