details:
  namespace: bookinfo-uat
  image: registry.arpo.ml/bookinfo/details
  tag: uat
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 9080
  healthCheckPath: "/health"
ingress:
  host: uat.arpo.ml
  path: "/details(/|$)(.*)"
  serviceType: ClusterIP
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
extraEnv:
  COMMIT_ID: CHANGEME