reviews:
  namespace: bookinfo-uat
  image: registry.arpo.ml/bookinfo/reviews
  tag: uat
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 9080
  healthCheckPath: "/health"
ingress:
  host: uat.arpo.ml
  path: "/reviews(/|$)(.*)"
  serviceType: ClusterIP
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
extraEnv:
  COMMIT_ID: CHANGEME
  ENABLE_RATINGS: true
  STAR_COLOR: yellow
  RATINGS_SERVICE: https://uat.arpo.ml/ratings