ratings:
  namespace: bookinfo-uat
  image: registry.arpo.ml/bookinfo/ratings
  tag: uat
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 8080
  healthCheckPath: "/health"
  mongodbPasswordExistingSecret: bookinfo-uat-ratings-mongodb-secret
ingress:
  host: uat.arpo.ml
  path: "/ratings(/|$)(.*)"
  serviceType: ClusterIP
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    cert-manager.io/cluster-issuer: "letsencrypt"
  tlsSecretName: letsencrypt-uat
extraEnv:
  SERVICE_VERSION: v2
  MONGO_DB_URL: mongodb://bookinfo-uat-ratings-mongodb:27017/?authSource=ratings
  MONGO_DB_NAME: ratings
  MONGO_DB_USERNAME: ratings-uat
  COMMIT_ID: CHANGEME