image:
  tag: 4.4.4-debian-10-r5
auth:
  enabled: true
  username: ratings-uat
  database: ratings
  existingSecret: bookinfo-uat-ratings-mongodb-secret
persistence:
  enabled: false
initdbScriptsConfigMap: bookinfo-uat-ratings-mongodb-initdb
extraEnvVars:
  - name: MONGODB_USERNAME
    value: ratings-uat
  - name: MONGODB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: bookinfo-uat-ratings-mongodb-secret
        key: mongodb-passwords
  - name: MONGODB_DATABASE
    value: ratings